In [6]:
import numpy as np
import pandas as pd

In [13]:
data = pd.read_csv("heart_disease_dataset.csv", delimiter = ";")

In [50]:
def sigmoid(x):
    return 1.0/(1+ np.exp(-x))

def sigmoid_derivative(x):
    return x * (1.0 - x)

def mse_loss(y_true, y_pred):
  # y_true and y_pred are numpy arrays of the same length.
  return ((y_true - y_pred) ** 2).mean()

def mse_loss_derivative(y_true, y_pred):
  # y_true and y_pred are numpy arrays of the same length.
  return (2*(y_true - y_pred))

class ArtificialNeuralNetwork:
    def __init__(self, x, y):
        self.IN            = x
        self.W1            = np.random.rand(self.IN.shape[1],6) 
        self.W2            = np.random.rand(6,4)
        self.W3            = np.random.rand(4,1)
        self.y             = y
        self.OUT           = np.zeros(self.y.shape)
        self.learning_rate = 0.3

    def feed_forward(self):
        self.HIDDEN_LAYER_1 = sigmoid(np.dot(self.IN, self.W1))
        self.HIDDEN_LAYER_2 = sigmoid(np.dot(self.HIDDEN_LAYER_1, self.W2))
        self.output = sigmoid(np.dot(self.HIDDEN_LAYER_2, self.W3))

    def back_propagate(self):
        # application of the chain rule to find derivative of the loss function with respect to W2 and W1
        print(self.HIDDEN_LAYER_2.T)
        d_W3 = np.dot(self.HIDDEN_LAYER_2.T, (mse_loss_derivative(self.y, self.output) * sigmoid_derivative(self.output)))
        print(self.HIDDEN_LAYER_1.T)
        d_W2 = np.dot(self.HIDDEN_LAYER_1.T, (mse_loss_derivative(self.y, self.output) * sigmoid_derivative(self.output)))
        print(d_W2)
        d_W1 = np.dot(self.IN.T,  (mse_loss_derivative(self.y, self.output) * sigmoid_derivative(self.output)))

        # update the weights with the derivative (slope) of the loss function
        self.W1 += self.learning_rate*d_W1
        self.W2 += self.learning_rate*d_W2
        self.W3 += self.learning_rate*d_W3

    def train(self, epochs,learning_rate):
        self.learning_rate=learning_rate
        for i in range(epochs):
            self.feed_forward()
            self.back_propagate()
        print("Successfully Trained the Model")
        print("Weights 1:", self.W1)
        print("Weights 2:", self.W2)
        print("Weights 3:", self.W3)
    
    def print_output(self):
        print(self.output)

In [51]:
data.columns = data.columns.str.replace(' ', '')
X = np.array(data.drop(columns=['target']))
y = np.reshape(np.array(data.target), (-1, 1))

In [57]:
m, n = X.shape
my, ny = y.shape

In [59]:
print(f"Features - Rows: {m} Columns: {n}")
print(f"Target - Rows: {my} Columns: {ny}")

Features - Rows: 303 Columns: 13
Target - Rows: 303 Columns: 1


Input will be each row from the Features column.
Output will be each row from target columns, with the dimensions shown above.

In each iteration(epoch), we find dot product of each layer with the previous layer and apply activation(sigmoid) function. In the back propagation, we find the weight error using mean squared error and adjust our weights by multiplying error by learning rate. 

In [52]:
epochs = 2
learning_rate = 0.5
ann = ArtificialNeuralNetwork(X,y)
ann.train(epochs, learning_rate)

[[0.88998774 0.88998774 0.88998774 ... 0.88998774 0.88998774 0.88998774]
 [0.97153014 0.97153014 0.97153014 ... 0.97153014 0.97153014 0.97153014]
 [0.76568221 0.76568221 0.76568221 ... 0.76568221 0.76568221 0.76568221]
 [0.92258085 0.92258085 0.92258085 ... 0.92258085 0.92258085 0.92258085]]
[[1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]]
[[-17.6543614]
 [-17.6543614]
 [-17.6543614]
 [-17.6543614]
 [-17.6543614]
 [-17.6543614]]
[[0.5 0.5 0.5 ... 0.5 0.5 0.5]
 [0.5 0.5 0.5 ... 0.5 0.5 0.5]
 [0.5 0.5 0.5 ... 0.5 0.5 0.5]
 [0.5 0.5 0.5 ... 0.5 0.5 0.5]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]
Successfully Trained the Model
Weights 1: [[-5.03297314e+02 -5.03600528e+02 -5.04093889e+02 -5.03606487e+02
  -5.03679952e+02 -5.03776948e+02]
 [-7.1593

C:\Users\SHAHIN~1\AppData\Local\Temp/ipykernel_17600/2686365357.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0/(1+ np.exp(-x))


We stop training when validation error is at minimum. When it reaches minimum, it means that our model has overfitted.